### ISSUE TITLE
设置触发时间后会反复刷屏

### ISSUE THREAD

**Issue by Hoshino-Yumetsuki** [LingLambda/koishi-plugin-hellomorning#1]
设置时间为：0 8 -1 -1
开启的附加消息为一言

根据日志记录时间判断会连续发一个小时的消息，即从8:00-9:00

![Screenshot_2024-10-04-10-35-53-67_9d26c6446fd7bb8e41d99b6262b17def](https://github.com/user-attachments/assets/ee15a2f7-926b-4626-b658-041abdf2c6a9)

**Comment by LingLambda** [comment]
感谢反馈
