### ISSUE TITLE
关于一言的改进建议

### ISSUE THREAD

**Issue by RikoNeko** [LingLambda/koishi-plugin-hellomorning#2]
希望可以让一言同时使用多个类型

**Comment by LingLambda** [comment]
已经添加了,市场更新可能要10分钟左右,感谢反馈

**Comment by RikoNeko** [comment]
话说一言、摸鱼日历的输出位置可以自定义吗？虽然看见支持了markdown，但是好像没有看见有自定义位置的文档

**Comment by LingLambda** [comment]
> 话说一言、摸鱼日历的输出位置可以自定义吗？虽然看见支持了markdown，但是好像没有看见有自定义位置的文档

暂时不支持,位置按照配置的顺序

**Comment by LingLambda** [comment]
> 话说一言、摸鱼日历的输出位置可以自定义吗？虽然看见支持了markdown，但是好像没有看见有自定义位置的文档

完成了[7d65a3](https://github.com/LingLambda/koishi-plugin-hellomorning/commit/7d65a3160211226799d9e1483802cca8fd1583a6)
