### ISSUE TITLE
每日内容无法使用markdown

### ISSUE THREAD

**Issue by Tigrex-Dai** [LingLambda/koishi-plugin-hellomorning#6]
无论是<markdown></markdown><br>标签还是转义符 \ 都用不了

**Comment by Tigrex-Dai** [comment]
应该是和json一些格式冲突，避免使用一些特殊符号

**Comment by LingLambda** [comment]
可以详细说说有哪些冲突吗，有空会修

**Comment by Tigrex-Dai** [comment]
您好，在markdown中我如果想要显示星号“*”，需要输入转义符“\”，但koishi的json导致我不输入\的时候会导致星号生效，显示不出星号，但输入\的时候会导致json自动变成双转义符，最终输出为"\*"。也就是怎么样我都无法单独显示出星号，不过这应该不是您插件这里的问题，如果能解决这个问题的话当然更好了^ ^

**Comment by LingLambda** [comment]
- 

> 您好，在markdown中我如果想要显示星号“*”，需要输入转义符“\”，但koishi的json导致我不输入\的时候会导致星号生效，显示不出星号，但输入\的时候会导致json自动变成双转义符，最终输出为"*"。也就是怎么样我都无法单独显示出星号，不过这应该不是您插件这里的问题，如果能解决这个问题的话当然更好了^ ^

感谢反馈,有空研究下
